sudo: false
language: node_js
node_js:
  - 'v10.19.0'
  - 'v12.16.1'
  - 'v13.12.0'
script:
  - commitlint-travis
  - run-s test docs check-clean
env:
  global:
    - BROWSER_STACK_USERNAME='snabbdombot1'
    - BROWSER_STACK_ACCESS_KEY='Wx2FUSehQLBf3haqHphd'
